version: '3.9'

services:
  db:
    image: postgres:13
    container_name: cocktails-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cocktails

  db_test:
    image: postgres:13
    container_name: cocktails-db-testing
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cocktails-test
    ports:
      - 5433:5432
    volumes:
      - postgres_db_test:/var/lib/postgresql/data
    networks:
      - cocktails

  api:
    image: api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?schema=public
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cocktails

networks:
  cocktails:

volumes:
  postgres:
  postgres_db_test:
